
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImFjYyI6InVzdWFyaW8yIiwiaWF0IjoxNzYwODAxMzQzfQ.ex88eON6Y8EqjS9eY2TbYbAxSvdJn-wMHKnjAPoUxSw
###----------------------MODE INVITE------------------------------

### Request Get Next Question (mode invite)
GET http://localhost:3000/question/invite/next?lastId=1
Accept: application/json


### Answer Question (Invite Mode)
POST http://localhost:3000/question/invite/answer
Content-Type: application/json

{
  "questionId": 1,
  "answer": "Inmutable"
}

###------------------------CREATE USER----------------------------

### Request Create
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "acc": "usuario2",
  "email": "correo1@ejemplo.com",
  "pass": "123456"
}

### request Login
Post http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "correo1@ejemplo.com",
  "pass": "123456"
}

###-----------------------REQUEST USER-----------------------------

### Post update progress user
POST  http://localhost:3000/question/progress
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "questionId": 1,
  "answer": "Inmutable"
}

### Get Read progress user
GET http://localhost:3000/question/progress
Authorization: Bearer {{token}}


### Toggle favorite (JWT)
POST http://localhost:3000/question/favorite/toggle
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "questionId": 5
}


### Get favorites
GET http://localhost:3000/question/favorites
Content-Type: application/json
Authorization: Bearer {{token}}

### comprueba favorite in user
GET http://localhost:3000/question/favorite/5
Authorization: Bearer {{token}}



